added L-02
aritode/rb_remaster pull request #1
Opened 2017-09-01 02:56 UTC by aritode

2017-09-01 05:15 UTC, iBublik requested changes

2017-09-01 05:15 UTC, iBublik commented on L-02/03_fibonacci.rb
> +  fibonacci_arr << fibonacci if fibonacci < max_value
Чтоб не дублировать проверку, можно записывать значение в переменную прямо в условии. Попробуй так сделать. Подсказка - присваивание возвращает результат.

2017-09-01 05:15 UTC, iBublik commented on L-02/04_letters.rb
> +dictionary = Hash.new
Хэши принято создавать с помощью литерала - `{}`

2017-09-01 05:15 UTC, iBublik commented on L-02/04_letters.rb
> +  i += 1
Чтоб не считать индекс вручную, посмотри метод `with_index`

2017-09-01 05:15 UTC, iBublik commented on L-02/05_dates.rb
> +}
В данном случая я бы взял обычный массив. Хэш тут не дает никаких преимуществ

2017-09-01 05:15 UTC, iBublik commented on L-02/05_dates.rb
> +months[:february] = 29 if year % 400 == 0 || year % 4 == 0
Условие неполное. Например, по этому условию 1900 - високосный год, но он таким не является

2017-09-01 05:15 UTC, iBublik commented on L-02/05_dates.rb
> +months.each do |key, value|
Цикл всегда будет проходить все месяца. Да, считает он правильно, но это все равно избыточно. Я бы рекомендовал использовать массив для месяцев, а тут обычный while использовть

2017-09-01 05:15 UTC, iBublik commented on L-02/06_shopping_sum.rb
> +products.each do |title, params|
Для преобразования одной коллекции в другую используй `map`

2017-09-02 06:35 UTC, iBublik commented on L-02/03_fibonacci.rb
> +while (fibonacci = fibonacci_arr[-1] + fibonacci_arr[-2]) && fibonacci < max_value
Я не просто так говорил, что присваивание возвращает результат. Можно еще сократить: `while (fibonacci = fibonacci_arr[-1] + fibonacci_arr[-2]) < max_value`

2017-09-02 06:35 UTC, iBublik commented on L-02/05_dates.rb
> +while month > 1 && month -= 1
Иногда действие (вроде присвоения) в условии помогает сократить код. Но вообще лучше избегать действий в условии, такой код сложнее читать.

2017-09-02 06:35 UTC, iBublik commented on L-02/06_shopping_sum.rb
> +final_price = products.map { |_title, params| params[:price] * params[:quantity] }.reduce(:+)
Можно сразу `reduce` делать (без промежуточного `map`)

2017-09-02 07:47 UTC, vkurennov approved these changes

2017-09-04 14:20 UTC, merged